version: "3.8"

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  db_init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_init
    command: python -m app.scraper.init_db
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./:/app

  selenium:
    image: selenium/standalone-chrome:99.0
    container_name: selenium
    shm_size: 8g  # Prevent crashes due to shared memory issues
    ports:
      - "4444:4444"  # Selenium WebDriver port
      - "7900:7900"  # VNC viewer port (optional, for debugging)

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./dumps:/app/dumps
      - ./logs:/app/logs
    command: celery -A app.scraper.tasks worker --loglevel=info
    mem_limit: 8g
    cpus: 2.0
    depends_on:
      - redis
      - postgres
      - selenium

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    # volumes:
    #   - ./:/app
    #   - ./dumps:/app/dumps
    #   - ./logs:/app/logs
    env_file:
      - .env
    command: celery -A app.scraper.tasks beat --loglevel=info
    depends_on:
      - redis
      - postgres
